### PR TITLE
Update CircleCI tests

### PR DESCRIPTION
**Pull request by alexisluque**

### CODE REVIEW

**Comment by jerriep** [comment]
@alexisluque Why are you setting the `CheckConsentNeeded` to `false` by default?

Does this interfere with your CircleCI tests?

**Comment by alexisluque** [comment]
@jerriep Yes, it does interfere with CircleCI test.

**Comment by aaguiarz** [comment]
@alexisluque How does it interfere?

**Comment by alexisluque** [comment]
The tests expects the login button to be visible to click it, but can't perform click because the consent bar is display over the login button.

**Comment by albertoperdomo** [comment]
Would it be possible to set `CheckConsentNeeded` to `false` only for the test environment, if there is such a thing? If so, would it be complex and make sense?

**Comment by jerriep** [comment]
@albertoperdomo Yes, this can be done

@alexisluque 

To do this, you need to change the `Startup` class as follows:

```csharp
public class Startup
{
    public Startup(IConfiguration configuration, IHostingEnvironment hostingEnvironment)
    {
        Configuration = configuration;
        HostingEnvironment = hostingEnvironment;
    }

    public IConfiguration Configuration { get; }
    public IHostingEnvironment HostingEnvironment { get; }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.Configure<CookiePolicyOptions>(options =>
        {
            // This lambda determines whether user consent for non-essential cookies is needed for a given request.
            options.CheckConsentNeeded = context => HostingEnvironment.IsProduction();
            options.MinimumSameSitePolicy = SameSiteMode.None;
        });

        //...
    }
}
```

This will ensure that the consent is only required in the production environment. You will also need to ensure that your CircleCI tests are not executed in the "Production" environment, by setting the `ASPNETCORE_ENVIRONMENT` to something other than "Production". ([See this for more](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1#set-the-environment))

**Comment by jerriep** [comment]
I think you can set the `ASPNETCORE_ENVIRONMENT` environment variable on this line, where you set the `ASPNETCORE_URLS` variable as well:

https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/blob/564ddeb1ae02cde1f9d4be3ef0a5a31acb50f310/.circleci/config.yml#L16

**Comment by alexisluque** [comment]
@jerriep it wasn't necessary update `config.yml` because the env variables settings defined on `launchSettings.json` override OS env variables, and ´ASPNETCORE_ENVIRONMENT´ is already set as `Development`.

**Comment by albertoperdomo** [comment]
Thanks @alexisluque @jerriep !

**Pull request merged**
